# Generated by Django 5.1.7 on 2025-03-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_ingredient_quantity_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
